<h2>Terms of Use</h2>

<p>The API and related services provided herein are made available "as is" and "as available" without any warranties or guarantees, express or implied. The provider of this API (hereinafter referred to as "the Host") does not assume any liability for the accuracy, reliability, completeness, or usefulness of the outputs generated by large language models (LLMs) accessed through this API.</p>

<p>Users acknowledge and agree that:</p>

<p>The Host shall not be responsible for any actions, decisions, or consequences arising from the use of this API or any outputs generated by LLMs.</p>

<p>The Host disclaims any liability for direct, indirect, incidental, consequential, or special damages, including but not limited to loss of data, business disruption, or reputational harm, even if advised of the possibility of such damages.</p>

<p>Users are solely responsible for evaluating the appropriateness, legality, and applicability of the API’s outputs in their respective contexts.</p>

<p>The use of this API does not establish any form of client-provider, advisor, or fiduciary relationship.</p>

<p>By accessing and using this API, users agree to the terms set forth in this disclaimer and waive any claims against the Host related to its usage.</p>
